// Long-form paid compat report, generated by Claude at unlock time.
//
// The static templates in compat.ts are the free-tier teaser / offline
// fallback; the PAID analysis is a saju-kid-grade report: ~12-13 titled
// sections, several sentences each, personalized to both charts, the
// relationship type, and the reading language. Generated ONCE per record
// (at payment confirmation) and stored, so repeat views cost nothing.

import type { SajuChart } from "./saju";
import type { CompatSection, Compatibility } from "./compat";
import type { ReportSection } from "./interpret";
import { analyzeStrength } from "./strength";
import { findSinsal } from "./sinsal";
import type { Lang } from "./i18n";

const MODEL = "claude-sonnet-5";

const LANG_NAME: Record<Lang, string> = {
  th: "Thai", en: "English", ko: "Korean",
};

interface AnthropicLike {
  messages: {
    create(args: unknown): Promise<{ content: Array<{ type: string; text?: string }> }>;
  };
}

let client: AnthropicLike | null | undefined;
function getClient(): AnthropicLike | null {
  if (client !== undefined) return client;
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) {
    client = null;
    return null;
  }
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const Anthropic = require("@anthropic-ai/sdk");
  client = new Anthropic({ apiKey: key }) as AnthropicLike;
  return client;
}

/** Tiny live-fire test of the generation stack — surfaces the exact API error. */
export async function generationHealth(): Promise<{
  ok: boolean;
  model: string;
  error?: string;
}> {
  try {
    const c = getClient();
    if (!c) return { ok: false, model: MODEL, error: "ANTHROPIC_API_KEY not set" };
    const res = await c.messages.create({
      model: MODEL,
      max_tokens: 16,
      messages: [{ role: "user", content: "ping — reply with pong only" }],
    });
    const text = res.content.find((b) => b.type === "text")?.text ?? "";
    return { ok: text.length > 0, model: MODEL };
  } catch (err) {
    return { ok: false, model: MODEL, error: String(err).slice(0, 400) };
  }
}

function pillarsOf(c: SajuChart): string {
  const p = (x: { gan: string; zhi: string } | null) => (x ? x.gan + x.zhi : "미상");
  return `시주 ${p(c.hour)} / 일주 ${p(c.day)} / 월주 ${p(c.month)} / 연주 ${p(c.year)}`;
}

const ROMANTIC = new Set(["lovers", "married", "talking"]);

// Each category owns ONE distinct topic so the report never repeats itself.
// label = the topic word that MUST lead the section title (so readers can
// scan the report structure at a glance); spec = the scope the body must
// stay inside. Reports are generated one category at a time, so these
// boundaries are what enforce separation.
interface ReportCategory {
  label: string;
  spec: string;
}

const ROMANTIC_CATEGORIES: ReportCategory[] = [
  { label: "전체 총평", spec: "조후·오행·궁합 점수의 큰 그림만. 세부 주제(성격·속궁합·금전 등)는 뒤 카테고리에서 다루므로 여기선 총론만." },
  { label: "각자의 성격", spec: "궁합이 아니라 두 사람 개인 소개. 각자의 일간·오행 기질을 인물 소개하듯 절반씩." },
  { label: "겉궁합", spec: "현실적·사회적 어울림만: 첫인상, 생활 리듬, 데이트 스타일, 남들 눈에 비치는 두 사람. 정서·육체 친밀감은 금지(속궁합 몫)." },
  { label: "속궁합", spec: "정서적·육체적 친밀감의 케미만 — 암합·충·합 근거로 구체적으로." },
  { label: "사랑 방식", spec: "각자 애정을 표현하고 받고 싶어하는 방식의 차이와 맞춤법만." },
  { label: "소통·갈등", spec: "다툴 때의 패턴과 화해법에만 집중." },
  { label: "금전 궁합", spec: "돈에 대한 태도 차이와 함께일 때의 경제 흐름·관리법만." },
  { label: "결혼운", spec: "결혼했을 때의 생활 모습, 결혼 적기, 안정도만. 돈 얘기는 금전 궁합 몫." },
  { label: "자녀운", spec: "아이를 낳는다면 어떤 기운의 아이인지, 양육 궁합만." },
  { label: "가족 인연", spec: "시댁·처가 등 양가와 주변 관계만." },
  { label: "장기 전망", spec: "권태기·위기 시점과 오래 가는 힘만." },
  { label: "관계 지침", spec: "관계를 지키는 구체적 액션 플랜만." },
  { label: "마무리", spec: "짧은 마무리 총평. 두 사람만의 개운 문구 한 줄 포함." },
];

const PLATONIC_CATEGORIES: ReportCategory[] = [
  { label: "전체 총평", spec: "두 사람 기운의 큰 그림만 — 세부는 뒤에서 다루므로 총론만." },
  { label: "각자의 성격", spec: "각자의 일간·오행 기질을 인물 소개하듯 절반씩." },
  { label: "케미", spec: "함께 있을 때의 어울림·분위기, 남들 눈에 비치는 관계만." },
  { label: "협업 궁합", spec: "함께 일이나 프로젝트를 할 때의 시너지만." },
  { label: "소통·갈등", spec: "부딪히는 지점과 푸는 법에만 집중." },
  { label: "신뢰", spec: "믿음과 의리를 쌓아가는 방식만." },
  { label: "금전 주의점", spec: "돈이 얽힐 때의 주의점만." },
  { label: "배울 점", spec: "서로에게 배울 점과 성장 포인트만." },
  { label: "장기 전망", spec: "장기적인 인연의 전망만." },
  { label: "관계 지침", spec: "관계를 지키는 구체적 액션 플랜만." },
  { label: "마무리", spec: "짧은 마무리 총평. 두 사람만의 개운 문구 한 줄 포함." },
];

// saju-kid-grade length: every category must read like a full consultation.
const LENGTH_RULE =
  `각 카테고리는 9~11문장, 공백 포함 400~500자(한국어 기준 — 태국어·영어도 같은 정보량). ` +
  `짧아도 되니 지루하지 않게: 뻔한 덕담과 하나마나한 문장은 빼고, 이 두 사람 사주에서만 나올 수 있는 ` +
  `구체적인 이야기만 써라. 실제 간지 글자와 일주 이름(예: 을해일주)을 인용하고 명리 근거(합·충·조후·용신·십신)를 짚되, ` +
  `용어 나열보다 생활 속 장면 하나를 생생하게 그려주는 쪽을 택하라. ` +
  `문장 리듬에 변화를 주고, 매 카테고리를 같은 패턴(예: "두 분은...")으로 시작하지 마라. ` +
  `문단 구성: 빈 줄(\\n\\n)로 구분된 2~3개 문단. ` +
  `분위기에 맞는 이모지(🌊 🔥 🌸 💞 🍀 ✨ 등)를 문단당 0~2개, 과하지 않게 자연스레 섞어라.`;

// Accuracy guardrails shared by the reading and compat prompts. The model
// tends to invent specific pillar-to-pillar 합/암합 (e.g. "월주와 시주 사이
// 술해 우합") that don't exist, and to overstate scattered 도화/화개. These
// rules keep the prose faithful to real 명리 positioning.
const ACCURACY_RULES =
  `\n\n[해석 정확도 규칙 — 반드시 지켜라]\n` +
  `1) 합·암합·우합·충은 '같은 자리'(예: 일지↔일지) 또는 '바로 옆 기둥'(예: 월지↔일지, 일지↔시지)의 지지끼리만 성립한다. ` +
  `월주-시주, 년주-시주, 년주-일주처럼 건너뛰어 떨어진 기둥끼리의 합/암합/우합은 존재하지 않으니 절대 지어내지 마라. ` +
  `어느 두 기둥인지 확신이 없으면 위치를 지목하지 말고 기운의 작용으로만 설명하라.\n` +
  `2) 흩어져 떨어진 암합은 언급하지 마라. 같은 자리 혹은 바로 옆자리 지지끼리의 암합만 다뤄라.\n` +
  `3) 도화살·화개살은 일지(또는 시지)에 자리한 '진도화·진화개'만 언급하라. 그 외 자리의 도화/화개는 없는 것으로 취급하고, 억지로 세게 가졌다고 하지 마라.\n` +
  `4) 사주에 '미상'(시주 등)으로 표시된 기둥은 그 기둥·지지에 관한 어떤 해석도 하지 마라.`;

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// One generation call for a slice of categories. Chunked + parallel so the
// full 12-13 category long-form report fits serverless time limits.
async function callChunk(
  c: AnthropicLike,
  system: string,
  context: string,
  cats: ReportCategory[],
  allCats: ReportCategory[],
  startNo: number,
  lang: Lang
): Promise<Array<{ title: string; body: string }> | null> {
  const prompt =
    context +
    `\n\n전체 리포트의 카테고리 구성 (겹치면 안 되는 다른 주제들):\n` +
    allCats.map((t, i) => `${i + 1}. ${t.label}`).join(" / ") +
    `\n\n이번엔 다음 카테고리만 작성해줘:\n` +
    cats.map((t, i) => `${startNo + i}. [${t.label}] ${t.spec}`).join("\n") +
    `\n\n범위 규칙: 위 [라벨]의 spec 범위 안에서만 써라. 전체 구성에 있는 다른 카테고리의 ` +
    `주제는 여기서 한 문장도 다루지 마라 (예: 겉궁합에서 속궁합 얘기 금지, 결혼운에서 돈 얘기 금지). ` +
    `\n\n${LENGTH_RULE}\n\n출력은 반드시 JSON 배열만: [{"title":"...","body":"..."}] — ` +
    `title은 반드시 "<카테고리명> — <감성 부제>" 형식 (카테고리명은 [라벨]을 ${LANG_NAME[lang]}로, ` +
    `부제는 이 커플만의 한 줄). 번호는 붙이지 마라. body는 본문. ` +
    `모든 텍스트는 ${LANG_NAME[lang]}(으)로.`;
  try {
    const res = await c.messages.create({
      model: MODEL,
      max_tokens: 3000,
      system: [{ type: "text", text: system, cache_control: { type: "ephemeral" } }],
      messages: [{ role: "user", content: prompt }],
    });
    const text = res.content.find((b) => b.type === "text")?.text ?? "";
    const json = text.slice(text.indexOf("["), text.lastIndexOf("]") + 1);
    const parsed = JSON.parse(json) as Array<{ title: string; body: string }>;
    if (!Array.isArray(parsed) || parsed.length === 0) return null;
    const out = parsed.map((sec) => ({
      title: String(sec.title ?? "").slice(0, 120),
      body: String(sec.body ?? ""),
    }));
    // Reject degenerate output — a rare "placeholder" stub, an empty body, or a
    // section far shorter than the length rule asks for. Returning null lets the
    // caller's retry loop regenerate this part instead of saving junk.
    if (out.some((s) => s.body.trim().length < 120 || s.body.trim() === s.title.trim())) {
      return null;
    }
    return out;
  } catch (err) {
    console.error("report chunk generation failed:", err);
    return null;
  }
}

/**
 * Translate ONE generated section into another language, preserving meaning,
 * length, paragraph breaks, and emoji — so every language shows the same
 * report. Client-orchestrated one call per section (like generation).
 */
export async function translateSection(
  title: string,
  body: string,
  lang: Lang
): Promise<{ title: string; body: string } | null> {
  const c = getClient();
  if (!c) return null;
  const prompt =
    `다음 사주 해석 섹션을 ${LANG_NAME[lang]}(으)로 번역해줘. ` +
    `의미와 정보량, 문단 구분(빈 줄), 이모지를 그대로 유지하고, 간지 한자(예: 丙戌, 乙亥)는 그대로 두되 ` +
    `명리 용어는 ${LANG_NAME[lang]} 독자가 이해할 수 있게 자연스럽게 옮겨라. 요약하거나 줄이지 마라. ` +
    `출력은 반드시 JSON 하나만: {"title":"...","body":"..."}\n\n` +
    `[제목] ${title}\n[본문]\n${body}`;
  try {
    const res = await c.messages.create({
      model: MODEL,
      max_tokens: 3000,
      messages: [{ role: "user", content: prompt }],
    });
    const text = res.content.find((b) => b.type === "text")?.text ?? "";
    const json = text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1);
    const p = JSON.parse(json) as { title: string; body: string };
    if (!p?.title || !p?.body) return null;
    // Reject a degenerate/placeholder translation so the retry loop re-runs it.
    if (String(p.body).trim().length < 120) return null;
    return { title: String(p.title).slice(0, 200), body: String(p.body) };
  } catch (err) {
    console.error("section translation failed:", err);
    return null;
  }
}

const READING_CATEGORIES: ReportCategory[] = [
  { label: "원국 총평", spec: "오행 흐름과 그릇의 크기, 시적인 비유 포함. 총론만." },
  { label: "성격", spec: "타고난 성격의 빛과 그림자만." },
  { label: "연애운", spec: "끌리는 상대의 기운, 사랑하는 방식, 주의점만." },
  { label: "결혼운", spec: "어울리는 배우자상과 결혼 생활의 모습만." },
  { label: "직업·적성", spec: "기운에 맞는 일과 피해야 할 일만." },
  { label: "재물운", spec: "돈이 들어오는 길과 새는 구멍만." },
  { label: "건강운", spec: "약한 오행과 몸 관리 포인트만." },
  { label: "인간관계", spec: "나를 돕는 귀인의 기운과 관계 패턴만." },
  { label: "대운 흐름", spec: "10년 단위 인생 리듬만." },
  { label: "올해·내년", spec: "올해와 내년의 운만." },
  { label: "개운법", spec: "용신 기반 행운 컬러·숫자·방향·습관 제안만." },
  { label: "마무리", spec: "짧은 마무리 총평. 이 사람만의 개운 문구 한 줄 포함." },
];

const CHUNK_SIZE = 1;

function readingPrompt(
  chart: SajuChart,
  profile: { name?: string; gender?: string },
  lang: Lang
): { system: string; context: string } {
  const s = analyzeStrength(chart, lang);
  const name = profile.name || (lang === "ko" ? "이 분" : lang === "th" ? "เจ้าชะตา" : "this person");
  const system =
    `너는 20년 경력의 명리학(사주) 상담가이자 감성 카피라이터다. ` +
    `따뜻하고 다정하며, 명리 용어(상생·조후·용신·억부·합·충 등)를 자연스럽게 녹여 ` +
    `근거 있는 해석을 쓴다. 단정적 협박은 금지, 실용적 조언 포함. ` +
    `반드시 ${LANG_NAME[lang]}(으)로만 작성한다.`;
  const sinsal = findSinsal(chart);
  const context =
    `사주 풀이 리포트를 작성해줘.\n\n` +
    `[의뢰인] ${name} (${profile.gender === "F" ? "여" : profile.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chart)}\n` +
    `일간: ${chart.dayMaster} / 오행 분포: ${JSON.stringify(chart.elementCounts)}\n` +
    `신강약: ${s.bandLabel} (지지율 ${s.supportRatio.toFixed(2)}) / 용신: ${s.favorable.join(", ")}\n` +
    `신살: ${sinsal.length ? sinsal.join(", ") : "없음"} (도화=매력, 홍염=달콤한 유혹, 화개=예술·고독, 역마=이동·변화 — 있으면 해석에 반드시 반영)\n` +
    `분석 노트: ${s.notes.join(" | ") || "없음"}\n` +
    `호칭 규칙: 의뢰인은 반드시 "${name}"(으)로 지칭하고, A나 '고객' 같은 임의 약칭을 만들지 마라.` +
    ACCURACY_RULES;
  return { system, context };
}

/** Number of generation parts for a report (client orchestrates one call per part). */
export function reportChunkCount(kind: "reading" | "compat", relationship?: string): number {
  const cats =
    kind === "reading"
      ? READING_CATEGORIES
      : ROMANTIC.has(relationship ?? "lovers")
      ? ROMANTIC_CATEGORIES
      : PLATONIC_CATEGORIES;
  return Math.ceil(cats.length / CHUNK_SIZE);
}

/** Generate ONE part (3 categories) of the reading report — fits any timeout. */
export async function generateReadingPart(
  chart: SajuChart,
  profile: { name?: string; gender?: string },
  lang: Lang,
  part: number
): Promise<Array<{ title: string; body: string }> | null> {
  const c = getClient();
  if (!c) return null;
  const chunks = chunk(READING_CATEGORIES, CHUNK_SIZE);
  if (part < 0 || part >= chunks.length) return null;
  const { system, context } = readingPrompt(chart, profile, lang);
  return callChunk(c, system, context, chunks[part], READING_CATEGORIES, part * CHUNK_SIZE + 1, lang);
}

/**
 * Long-form paid saju reading (~12 titled sections). Returns null when no API
 * key is set or generation fails — callers keep the static template unlock.
 */
export async function generateReadingReport(
  chart: SajuChart,
  profile: { name?: string; gender?: string },
  lang: Lang
): Promise<ReportSection[] | null> {
  const c = getClient();
  if (!c) return null;

  const { system, context } = readingPrompt(chart, profile, lang);
  const chunks = chunk(READING_CATEGORIES, CHUNK_SIZE);
  let start = 1;
  const jobs = chunks.map((cs) => {
    const job = callChunk(c, system, context, cs, READING_CATEGORIES, start, lang);
    start += cs.length;
    return job;
  });
  const results = await Promise.all(jobs);
  const all = results.filter(Boolean).flat() as Array<{ title: string; body: string }>;
  if (all.length < READING_CATEGORIES.length) return null; // full report or nothing
  return all.map((sec, i) => ({
    key: `gen${i + 1}`,
    title: sec.title,
    body: sec.body,
    locked: false,
  }));
}

// The engine's factual cross-chart combination list (positions included) —
// the ONLY 합/암합/충 the AI may cite. Old stored results lack `combos`.
function comboList(result: Compatibility, nameA: string, nameB: string): string {
  const list = (result.combos ?? [])
    .map((c) => `- ${c.replaceAll("{A}", nameA).replaceAll("{B}", nameB)}`)
    .join("\n");
  if (!list) return "";
  return (
    `\n\n[확인된 합·충 목록 — 위치까지 검증된 사실. 합·암합·우합·삼합·충은 이 목록에 있는 것만, ` +
    `적힌 위치 그대로 언급하라. 목록에 없는 합을 지어내면 안 된다]\n${list}`
  );
}

function compatPrompt(
  chartA: SajuChart,
  chartB: SajuChart,
  profiles: { a?: { name?: string; gender?: string }; b?: { name?: string; gender?: string } },
  result: Compatibility
): { system: string; context: string; cats: ReportCategory[]; lang: Lang } {
  const lang = result.lang ?? "th";
  const relationship = result.relationship ?? "lovers";
  const romantic = ROMANTIC.has(relationship);
  // Refer to people by their entered name; fall back to a gendered label —
  // never "A"/"B".
  const personLabel = (
    p: { name?: string; gender?: string } | undefined,
    ord: number
  ): string => {
    if (p?.name?.trim()) return p.name.trim();
    if (p?.gender === "F") return lang === "ko" ? "여자분" : lang === "th" ? "ฝ่ายหญิง" : "the woman";
    if (p?.gender === "M") return lang === "ko" ? "남자분" : lang === "th" ? "ฝ่ายชาย" : "the man";
    return lang === "ko" ? `${ord === 1 ? "첫" : "두"} 번째 분` : lang === "th" ? `คนที่ ${ord}` : `person ${ord}`;
  };
  const nameA = personLabel(profiles.a, 1);
  const nameB = personLabel(profiles.b, 2);

  const system =
    `너는 20년 경력의 명리학(사주) 상담가이자 감성 카피라이터다. ` +
    `따뜻하고 다정하며, 명리 용어(상생·조후·용신·합·충 등)를 자연스럽게 녹여 ` +
    `근거 있는 해석을 쓴다. 단정적 협박은 금지, 실용적 조언 포함. ` +
    `반드시 ${LANG_NAME[lang]}(으)로만 작성한다.`;

  // Engine findings (배우자성·천을귀인·신살·암합·조후…) — the long report must
  // build on these, not contradict them.
  const points = (result.sections ?? [])
    .filter((s) => s.key.startsWith("note"))
    .map((s) => `- ${s.title ? s.title + ": " : ""}${s.body}`)
    .join("\n");
  const sinsalLine = (c: SajuChart) => {
    const ss = findSinsal(c);
    return ss.length ? ss.join(", ") : "없음";
  };
  const context =
    `두 사람의 궁합 리포트를 작성해줘.\n\n` +
    `[${nameA}] (${profiles.a?.gender === "F" ? "여" : profiles.a?.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chartA)}\n오행 분포: ${JSON.stringify(chartA.elementCounts)}\n신살: ${sinsalLine(chartA)}\n\n` +
    `[${nameB}] (${profiles.b?.gender === "F" ? "여" : profiles.b?.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chartB)}\n오행 분포: ${JSON.stringify(chartB.elementCounts)}\n신살: ${sinsalLine(chartB)}\n\n` +
    `관계: ${relationship} / 궁합 점수: ${result.score}%` +
    (romantic && typeof result.intimate === "number"
      ? ` / 속궁합: ${result.intimate}%`
      : "") +
    (points
      ? `\n\n[엔진 분석 포인트 — 배우자성(관성·재성)·천을귀인·신살·암합 등. 반드시 이 근거들을 해석에 녹여라]\n${points}`
      : "") +
    comboList(result, nameA, nameB) +
    `\n\n호칭 규칙: 두 사람은 반드시 "${nameA}"와(과) "${nameB}"로만 지칭하라. ` +
    `"A", "B", "사람1" 같은 임의 약칭을 절대 만들지 마라.` +
    ACCURACY_RULES;

  return { system, context, cats: romantic ? ROMANTIC_CATEGORIES : PLATONIC_CATEGORIES, lang };
}

/** Generate ONE part (3 categories) of the compat report — fits any timeout. */
export async function generateCompatPart(
  chartA: SajuChart,
  chartB: SajuChart,
  profiles: { a?: { name?: string; gender?: string }; b?: { name?: string; gender?: string } },
  result: Compatibility,
  part: number
): Promise<Array<{ title: string; body: string }> | null> {
  const c = getClient();
  if (!c) return null;
  const { system, context, cats, lang } = compatPrompt(chartA, chartB, profiles, result);
  const chunks = chunk(cats, CHUNK_SIZE);
  if (part < 0 || part >= chunks.length) return null;
  return callChunk(c, system, context, chunks[part], cats, part * CHUNK_SIZE + 1, lang);
}

/**
 * Generate the long-form paid report. Returns null when no API key is set or
 * generation fails — callers fall back to the static template unlock.
 */
export async function generateCompatReport(
  chartA: SajuChart,
  chartB: SajuChart,
  profiles: { a?: { name?: string; gender?: string }; b?: { name?: string; gender?: string } },
  result: Compatibility
): Promise<CompatSection[] | null> {
  const c = getClient();
  if (!c) return null;

  const { system, context, cats, lang } = compatPrompt(chartA, chartB, profiles, result);
  const chunks = chunk(cats, CHUNK_SIZE);
  let start = 1;
  const jobs = chunks.map((cs) => {
    const job = callChunk(c, system, context, cs, cats, start, lang);
    start += cs.length;
    return job;
  });
  const results = await Promise.all(jobs);
  const all = results.filter(Boolean).flat() as Array<{ title: string; body: string }>;
  if (all.length < cats.length) return null; // full report or nothing
  return all.map((sec, i) => ({
    key: `gen${i + 1}`,
    title: sec.title,
    body: sec.body,
    locked: false,
  }));
}
