// Long-form paid compat report, generated by Claude at unlock time.
//
// The static templates in compat.ts are the free-tier teaser / offline
// fallback; the PAID analysis is a saju-kid-grade report: ~12-13 titled
// sections, several sentences each, personalized to both charts, the
// relationship type, and the reading language. Generated ONCE per record
// (at payment confirmation) and stored, so repeat views cost nothing.

import type { SajuChart } from "./saju";
import type { CompatSection, Compatibility } from "./compat";
import type { ReportSection } from "./interpret";
import { analyzeStrength } from "./strength";
import type { Lang } from "./i18n";

const MODEL = "claude-sonnet-5";

const LANG_NAME: Record<Lang, string> = {
  th: "Thai", en: "English", ko: "Korean",
};

interface AnthropicLike {
  messages: {
    create(args: unknown): Promise<{ content: Array<{ type: string; text?: string }> }>;
  };
}

let client: AnthropicLike | null | undefined;
function getClient(): AnthropicLike | null {
  if (client !== undefined) return client;
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) {
    client = null;
    return null;
  }
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const Anthropic = require("@anthropic-ai/sdk");
  client = new Anthropic({ apiKey: key }) as AnthropicLike;
  return client;
}

function pillarsOf(c: SajuChart): string {
  const p = (x: { gan: string; zhi: string } | null) => (x ? x.gan + x.zhi : "미상");
  return `시주 ${p(c.hour)} / 일주 ${p(c.day)} / 월주 ${p(c.month)} / 연주 ${p(c.year)}`;
}

const ROMANTIC = new Set(["lovers", "married", "talking"]);

const ROMANTIC_CATEGORIES: string[] = [
  "전체 형국 총평 (조후·오행 흐름의 큰 그림, 시적인 비유 포함)",
  "첫인상과 끌림의 이유",
  "서로가 서로를 바라보는 시선 (각자 상대를 어떻게 느끼는지)",
  "상대의 속마음 (겉으로 말하지 않는 진심)",
  "서로에게 바라는 것 (이상형과 현실의 갭)",
  "소통 방식과 갈등 패턴 (싸울 때 어떻게 다른지, 화해법)",
  "속궁합 (육체적·정서적 친밀감의 케미 — 암합·충·합의 근거를 들어 아주 구체적으로)",
  "결혼운 (결혼했을 때의 모습, 적기, 경제적 안정도)",
  "재물운과 노후 (함께일 때의 경제 흐름)",
  "자녀운 (아이를 낳는다면 어떤 기운의 아이인지)",
  "양가 가족과의 인연 (시댁·처가와의 관계)",
  "관계를 지키는 결정적 지침 (구체적 액션 플랜 포함)",
  "마무리 총평 (두 사람만의 개운 문구 한 줄 포함)",
];

const PLATONIC_CATEGORIES: string[] = [
  "전체 형국 총평 (두 사람 기운의 큰 그림, 비유 포함)",
  "첫 만남과 가까워진 이유",
  "서로가 서로를 바라보는 시선",
  "상대의 속마음 (겉으로 말하지 않는 진심)",
  "함께 일할 때의 시너지 (협업 케미)",
  "소통 방식과 갈등 패턴 (부딪히는 지점, 푸는 법)",
  "신뢰를 쌓는 법",
  "금전·거래에서의 주의점",
  "서로에게 배울 점",
  "장기적인 인연의 전망",
  "관계를 지키는 결정적 지침 (구체적 액션 플랜 포함)",
  "마무리 총평 (두 사람만의 개운 문구 한 줄 포함)",
];

// saju-kid-grade length: every category must read like a full consultation.
const LENGTH_RULE =
  `각 카테고리는 반드시 하나의 긴 문단형 리포트로: 15문장 이상, 공백 포함 700자 이상(한국어 기준 — ` +
  `태국어·영어도 같은 정보량). 실제 간지 글자와 일주 이름(예: 을해일주, 병술일주)을 인용하고, ` +
  `명리 근거(합·충·암합·조후·용신·십신)를 짚으며, 생활 속 구체적 장면과 실용 조언(인테리어, 말버릇, ` +
  `시기 등)까지 담아라. 짧고 두루뭉술한 문장은 금지.`;

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// One generation call for a slice of categories. Chunked + parallel so the
// full 12-13 category long-form report fits serverless time limits.
async function callChunk(
  c: AnthropicLike,
  system: string,
  context: string,
  cats: string[],
  startNo: number,
  lang: Lang
): Promise<Array<{ title: string; body: string }> | null> {
  const prompt =
    context +
    `\n\n이건 전체 리포트 중 일부야. 다음 카테고리들만 작성해줘:\n` +
    cats.map((t, i) => `${startNo + i}. ${t}`).join("\n") +
    `\n\n${LENGTH_RULE}\n\n출력은 반드시 JSON 배열만: [{"title":"...","body":"..."}] — ` +
    `title은 각 카테고리를 감성적인 한 줄 제목으로 (번호 없이), body는 본문. ` +
    `모든 텍스트는 ${LANG_NAME[lang]}(으)로.`;
  try {
    const res = await c.messages.create({
      model: MODEL,
      max_tokens: 9000,
      system: [{ type: "text", text: system, cache_control: { type: "ephemeral" } }],
      messages: [{ role: "user", content: prompt }],
    });
    const text = res.content.find((b) => b.type === "text")?.text ?? "";
    const json = text.slice(text.indexOf("["), text.lastIndexOf("]") + 1);
    const parsed = JSON.parse(json) as Array<{ title: string; body: string }>;
    if (!Array.isArray(parsed) || parsed.length === 0) return null;
    return parsed.map((sec) => ({
      title: String(sec.title).slice(0, 120),
      body: String(sec.body),
    }));
  } catch (err) {
    console.error("report chunk generation failed:", err);
    return null;
  }
}

const READING_CATEGORIES: string[] = [
  "원국 총평 (오행 흐름과 그릇의 크기, 시적인 비유 포함)",
  "타고난 성격의 빛과 그림자",
  "연애운 (끌리는 상대의 기운, 사랑하는 방식, 주의점)",
  "결혼운 (어울리는 배우자상, 결혼 생활의 모습)",
  "직업운과 적성 (기운에 맞는 일, 피해야 할 일)",
  "재물운 (돈이 들어오는 길과 새는 구멍)",
  "건강운 (약한 오행과 몸 관리 포인트)",
  "인간관계와 귀인 (나를 돕는 사람의 기운)",
  "대운의 큰 흐름 (10년 단위 인생 리듬)",
  "올해와 내년의 운",
  "개운법 (용신 기반 행운 컬러·숫자·방향·습관 제안)",
  "마무리 총평 (이 사람만의 개운 문구 한 줄 포함)",
];

/**
 * Long-form paid saju reading (~12 titled sections). Returns null when no API
 * key is set or generation fails — callers keep the static template unlock.
 */
export async function generateReadingReport(
  chart: SajuChart,
  profile: { name?: string; gender?: string },
  lang: Lang
): Promise<ReportSection[] | null> {
  const c = getClient();
  if (!c) return null;

  const s = analyzeStrength(chart, lang);
  const name = profile.name || (lang === "ko" ? "이 분" : lang === "th" ? "เจ้าชะตา" : "this person");

  const system =
    `너는 20년 경력의 명리학(사주) 상담가이자 감성 카피라이터다. ` +
    `따뜻하고 다정하며, 명리 용어(상생·조후·용신·억부·합·충 등)를 자연스럽게 녹여 ` +
    `근거 있는 해석을 쓴다. 단정적 협박은 금지, 실용적 조언 포함. ` +
    `반드시 ${LANG_NAME[lang]}(으)로만 작성한다.`;

  const context =
    `사주 풀이 리포트를 작성해줘.\n\n` +
    `[의뢰인] ${name} (${profile.gender === "F" ? "여" : profile.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chart)}\n` +
    `일간: ${chart.dayMaster} / 오행 분포: ${JSON.stringify(chart.elementCounts)}\n` +
    `신강약: ${s.bandLabel} (지지율 ${s.supportRatio.toFixed(2)}) / 용신: ${s.favorable.join(", ")}\n` +
    `분석 노트: ${s.notes.join(" | ") || "없음"}`;

  const chunks = chunk(READING_CATEGORIES, 4);
  let start = 1;
  const jobs = chunks.map((cs) => {
    const job = callChunk(c, system, context, cs, start, lang);
    start += cs.length;
    return job;
  });
  const results = await Promise.all(jobs);
  const all = results.filter(Boolean).flat() as Array<{ title: string; body: string }>;
  if (all.length < 6) return null;
  return all.map((sec, i) => ({
    key: `gen${i + 1}`,
    title: sec.title,
    body: sec.body,
    locked: false,
  }));
}

/**
 * Generate the long-form paid report. Returns null when no API key is set or
 * generation fails — callers fall back to the static template unlock.
 */
export async function generateCompatReport(
  chartA: SajuChart,
  chartB: SajuChart,
  profiles: { a?: { name?: string; gender?: string }; b?: { name?: string; gender?: string } },
  result: Compatibility
): Promise<CompatSection[] | null> {
  const c = getClient();
  if (!c) return null;

  const lang = result.lang ?? "th";
  const relationship = result.relationship ?? "lovers";
  const romantic = ROMANTIC.has(relationship);
  const nameA = profiles.a?.name || (lang === "ko" ? "첫 번째 분" : "A");
  const nameB = profiles.b?.name || (lang === "ko" ? "두 번째 분" : "B");

  const system =
    `너는 20년 경력의 명리학(사주) 상담가이자 감성 카피라이터다. ` +
    `따뜻하고 다정하며, 명리 용어(상생·조후·용신·합·충 등)를 자연스럽게 녹여 ` +
    `근거 있는 해석을 쓴다. 단정적 협박은 금지, 실용적 조언 포함. ` +
    `반드시 ${LANG_NAME[lang]}(으)로만 작성한다.`;

  const context =
    `두 사람의 궁합 리포트를 작성해줘.\n\n` +
    `[사람 A] ${nameA} (${profiles.a?.gender === "F" ? "여" : profiles.a?.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chartA)}\n오행 분포: ${JSON.stringify(chartA.elementCounts)}\n\n` +
    `[사람 B] ${nameB} (${profiles.b?.gender === "F" ? "여" : profiles.b?.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chartB)}\n오행 분포: ${JSON.stringify(chartB.elementCounts)}\n\n` +
    `관계: ${relationship} / 궁합 점수: ${result.score}%` +
    (romantic && typeof result.intimate === "number"
      ? ` / 속궁합: ${result.intimate}%`
      : "");

  const cats = romantic ? ROMANTIC_CATEGORIES : PLATONIC_CATEGORIES;
  const chunks = chunk(cats, 5);
  let start = 1;
  const jobs = chunks.map((cs) => {
    const job = callChunk(c, system, context, cs, start, lang);
    start += cs.length;
    return job;
  });
  const results = await Promise.all(jobs);
  const all = results.filter(Boolean).flat() as Array<{ title: string; body: string }>;
  if (all.length < 6) return null;
  return all.map((sec, i) => ({
    key: `gen${i + 1}`,
    title: sec.title,
    body: sec.body,
    locked: false,
  }));
}
