// Long-form paid compat report, generated by Claude at unlock time.
//
// The static templates in compat.ts are the free-tier teaser / offline
// fallback; the PAID analysis is a saju-kid-grade report: ~12-13 titled
// sections, several sentences each, personalized to both charts, the
// relationship type, and the reading language. Generated ONCE per record
// (at payment confirmation) and stored, so repeat views cost nothing.

import type { SajuChart } from "./saju";
import type { CompatSection, Compatibility } from "./compat";
import type { Lang } from "./i18n";

const MODEL = "claude-sonnet-5";

const LANG_NAME: Record<Lang, string> = {
  th: "Thai", en: "English", ko: "Korean",
};

interface AnthropicLike {
  messages: {
    create(args: unknown): Promise<{ content: Array<{ type: string; text?: string }> }>;
  };
}

let client: AnthropicLike | null | undefined;
function getClient(): AnthropicLike | null {
  if (client !== undefined) return client;
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) {
    client = null;
    return null;
  }
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const Anthropic = require("@anthropic-ai/sdk");
  client = new Anthropic({ apiKey: key }) as AnthropicLike;
  return client;
}

function pillarsOf(c: SajuChart): string {
  const p = (x: { gan: string; zhi: string } | null) => (x ? x.gan + x.zhi : "미상");
  return `시주 ${p(c.hour)} / 일주 ${p(c.day)} / 월주 ${p(c.month)} / 연주 ${p(c.year)}`;
}

const ROMANTIC = new Set(["lovers", "married", "talking"]);

const ROMANTIC_CATEGORIES = `1. 전체 형국 총평 (조후·오행 흐름의 큰 그림, 시적인 비유 포함)
2. 첫인상과 끌림의 이유
3. 서로가 서로를 바라보는 시선 (각자 상대를 어떻게 느끼는지)
4. 상대의 속마음 (겉으로 말하지 않는 진심)
5. 서로에게 바라는 것 (이상형과 현실의 갭)
6. 소통 방식과 갈등 패턴 (싸울 때 어떻게 다른지, 화해법)
7. 속궁합 (육체적·정서적 친밀감의 케미)
8. 결혼운 (결혼했을 때의 모습, 적기)
9. 재물운과 노후 (함께일 때의 경제 흐름)
10. 자녀운 (아이를 낳는다면 어떤 기운의 아이인지)
11. 양가 가족과의 인연
12. 관계를 지키는 결정적 지침 (구체적 액션 플랜 포함)
13. 마무리 총평 (두 사람만의 개운 문구 한 줄 포함)`;

const PLATONIC_CATEGORIES = `1. 전체 형국 총평 (두 사람 기운의 큰 그림, 비유 포함)
2. 첫 만남과 가까워진 이유
3. 서로가 서로를 바라보는 시선
4. 상대의 속마음 (겉으로 말하지 않는 진심)
5. 함께 일할 때의 시너지 (협업 케미)
6. 소통 방식과 갈등 패턴 (부딪히는 지점, 푸는 법)
7. 신뢰를 쌓는 법
8. 금전·거래에서의 주의점
9. 서로에게 배울 점
10. 장기적인 인연의 전망
11. 관계를 지키는 결정적 지침 (구체적 액션 플랜 포함)
12. 마무리 총평 (두 사람만의 개운 문구 한 줄 포함)`;

/**
 * Generate the long-form paid report. Returns null when no API key is set or
 * generation fails — callers fall back to the static template unlock.
 */
export async function generateCompatReport(
  chartA: SajuChart,
  chartB: SajuChart,
  profiles: { a?: { name?: string; gender?: string }; b?: { name?: string; gender?: string } },
  result: Compatibility
): Promise<CompatSection[] | null> {
  const c = getClient();
  if (!c) return null;

  const lang = result.lang ?? "th";
  const relationship = result.relationship ?? "lovers";
  const romantic = ROMANTIC.has(relationship);
  const nameA = profiles.a?.name || (lang === "ko" ? "첫 번째 분" : "A");
  const nameB = profiles.b?.name || (lang === "ko" ? "두 번째 분" : "B");

  const system =
    `너는 20년 경력의 명리학(사주) 상담가이자 감성 카피라이터다. ` +
    `따뜻하고 다정하며, 명리 용어(상생·조후·용신·합·충 등)를 자연스럽게 녹여 ` +
    `근거 있는 해석을 쓴다. 단정적 협박은 금지, 실용적 조언 포함. ` +
    `반드시 ${LANG_NAME[lang]}(으)로만 작성한다.`;

  const prompt =
    `두 사람의 궁합 리포트를 작성해줘.\n\n` +
    `[사람 A] ${nameA} (${profiles.a?.gender === "F" ? "여" : profiles.a?.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chartA)}\n오행 분포: ${JSON.stringify(chartA.elementCounts)}\n\n` +
    `[사람 B] ${nameB} (${profiles.b?.gender === "F" ? "여" : profiles.b?.gender === "M" ? "남" : "성별 미상"})\n` +
    `사주: ${pillarsOf(chartB)}\n오행 분포: ${JSON.stringify(chartB.elementCounts)}\n\n` +
    `관계: ${relationship} / 궁합 점수: ${result.score}%` +
    (romantic && typeof result.intimate === "number"
      ? ` / 속궁합: ${result.intimate}%`
      : "") +
    `\n\n다음 카테고리로 작성 (각 섹션 4~8문장, 두 사람의 실제 사주 글자를 인용하며):\n` +
    (romantic ? ROMANTIC_CATEGORIES : PLATONIC_CATEGORIES) +
    `\n\n출력은 반드시 JSON 배열만: [{"title":"...","body":"..."}] — ` +
    `title은 각 카테고리를 감성적인 한 줄 제목으로 (번호 없이), body는 본문. ` +
    `모든 텍스트는 ${LANG_NAME[lang]}(으)로.`;

  try {
    const res = await c.messages.create({
      model: MODEL,
      max_tokens: 8000,
      system: [{ type: "text", text: system, cache_control: { type: "ephemeral" } }],
      messages: [{ role: "user", content: prompt }],
    });
    const text = res.content.find((b) => b.type === "text")?.text ?? "";
    const json = text.slice(text.indexOf("["), text.lastIndexOf("]") + 1);
    const parsed = JSON.parse(json) as Array<{ title: string; body: string }>;
    if (!Array.isArray(parsed) || parsed.length < 6) return null;
    return parsed.map((sec, i) => ({
      key: `gen${i + 1}`,
      title: String(sec.title).slice(0, 120),
      body: String(sec.body),
      locked: false,
    }));
  } catch (err) {
    console.error("compat report generation failed (fallback to templates):", err);
    return null;
  }
}
